### ISSUE TITLE
not open vm ip 

### ISSUE THREAD

**Issue by vahidalvandi** [bjoernbessert/haproxy-cert-otf#6]
i installed [bjoernbessert](https://github.com/bjoernbessert) from one vm instaled complete my vm ip is 192.168.1.100 but not return anything .  aslo in vm terminal **curl 127.0.0.1**   return curl: (52) Empty reply from server

vahid@haproxy:~/haproxy-cert-otf-master$ docker-compose up -d
/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Starting haproxy-cert-otf-master_apache_1 ... **done**
Starting haproxy-cert-otf-master_ca-api_1 ... **done**
Starting haproxy-cert-otf-master_haproxy_1 ... **done**

**Comment by bjoernbessert** [comment]
How to test this project you can look at:
[01_localca.bats](https://github.com/bjoernbessert/haproxy-cert-otf/blob/master/tests/01_localca.bats)
[test_helper.bash](https://github.com/bjoernbessert/haproxy-cert-otf/blob/master/tests/test_helper.bash)

For example:
`curl -v --resolve sub1.example.local:443:127.0.0.1 "https://sub1.example.local"`
